### PR TITLE
Add username to cluster context name

### LINKED ISSUE #12: small change in generated kubeconfig
can you please make the context name to be username@clustername instead of clustername as is now? this would be useful for admins which are testing many users on the same cluster.

it seems to be a small change in internal/kubeconfig/create-kubeconfig.go, something like

--- a/internal/kubeconfig/create-kubeconfig.go
+++ b/internal/kubeconfig/create-kubeconfig.go
@@ -35,7 +35,7 @@ users:
     user:
       client-certificate-data: %s
       client-key-data: %s`,
-               clusterName, clusterName, clusterControlPlaceAddress, caBasebase64, clusterName, username, clusterName, username, crtBase64, privateKeyBase64)
+               clusterName, clusterName, clusterControlPlaceAddress, caBasebase64, clusterName, username, username+"@"+clusterName, username, crtBase64, privateKeyBase64)
 
        return kubeconfigYAML
 }

### PR DESCRIPTION
**Pull request by iknite**
Closes #12

### CODE REVIEW

**Comment by jnardiello** [comment]
Has anyone tried it locally?

**Comment by phisco** [comment]
@jnardiello tests are present, but are not run against PRs currently. We are working on it.

**Comment by iknite** [comment]
@jnardiello I did run the simple test for this function but not the complete repo.

**Comment by jnardiello** [comment]
All clear. LGTM +1

**Comment by jnardiello** [comment]
Thanks a lot for adding this @iknite !

**Pull request merged**
