### PR TITLE
add NodePort port options for helm charts values

### PR DESCRIPTION
**Pull request by runzhliu**

### CODE REVIEW

**Comment by luigibarbato** [comment]
@runzhliu It looks really good, thanks for the contribution. Could you please resolve the conflicts and update the helm chart version? Thanks :)

**Comment by runzhliu** [comment]
@luigibarbato it's alright ;)

**Comment by luigibarbato** [comment]
> @luigibarbato it's alright ;)

Awesome! The last thing, update the helm chart at the current master's version please: `1.8.0-rc1`

**Comment by runzhliu** [comment]
done.

**Review by luigibarbato — APPROVED** [review]
SBAM

**Pull request merged**
