### PR TITLE
Add metrics roles to enable lens metrics

### LINKED ISSUE #43: Lens not showing metrics to user who can only access some namespaces
Is there a way that even though the user is only granted full access to some namespaces, the user still can see the metrics from Lens app? Because the user can't see the namespaces resources this way.

### PR DESCRIPTION
**Pull request by angelbarrera92**
Fixes #43 

The new RBAC configuration has been copy pasted from: https://github.com/lensapp/lens/pull/644/files#diff-e8fd9c95df786da51f13c3a7442a1d88b3ac4294b786bc268ac92a4072bf50e7R5-R198

> Service Accounts with this cluster role will be able to see cluster metrics and pod metrics but will not be able to see secrets and service accounts. The cluster role does not allow for modifying K8s resources (update, create or delete). It also explicitly lists Kubernetes' little-known sub-resources (which is why service accounts bound to the base `view` cluster role cannot see metrics in Lens).
> This is ideal for giving particular users access to a read only user to use in Lens or for dashboards left up in the office.

*Source: https://github.com/lensapp/lens/pull/644*

The main "problem" here is that to see metrics you need, at least, read-only permission cluster-wide because of how lens implements the metrics.

Thanks!

### CODE REVIEW

**Comment by phisco** [comment]
mmm maybe add a comment in the yaml file in order not to forget where these rules come from

**Comment by angelbarrera92** [comment]
> mmm maybe add a comment in the yaml file in order not to forget where these rules come from

Done!

**Comment by phisco** [comment]
Lgtm 👌

**Review by phisco — APPROVED** [review]

**Review by ralgozino — APPROVED** [review]
lgtm

**Pull request merged**
